steps:
- name: 'ubuntu'
  args: ['sh', './cb_setup.sh']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=knative.dev/test-infra']
- name: 'ubuntu'
  args: ['sh', './cb_test.sh']
